# Generated by Django 4.2.6 on 2023-10-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('mdrrmc', 'MDRRMC Admin'), ('barangay', 'Barangay Admin')], default='mdrrmc', max_length=8),
        ),
    ]
